project:
  type: book

book:
  title: "EVOLUTIOSoc: A Meta-Framework for Complex Social Systems"
  author: "Francisco J Navarro-Meneses"
  date: "22/02/2024"
  chapters:
    - index.qmd
    - intro_2.qmd
    - theory.qmd
    - methodology.qmd
    - results.qmd
    - discussion.qmd
    - conclusion.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

