project:
  type: book

book:
  title: "Towards an Integrative Meta-Framework for the Evolutionary Analysis of the Firm"
  author: "Francisco J Navarro-Meneses"
  date: "11/28/2024"
  chapters:
    - index.qmd
    - 1_intro.qmd
    - 2_challenges.qmd
    - 3_meta-framework.qmd
    - 4_methodology.qmd
    - 5_results.qmd
    - 6_discussion.qmd
    - theory.qmd
    - conclusion.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

