project:
  type: book

book:
  title: "mybiology"
  author: "Norah Jones"
  date: "22/12/2023"
  chapters:
    - index.qmd
    - reasons.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

