# Analogies

## Why Analogies?

"Economics may gain much, as it already has, from the concepts and methods of analysis of other disciplines." [@alchian1950uncertainty]

"The purpose of analogical reasoning in which we consciously and systematically apply the explanation of one series of events to another very different series of events is to help us better to understand the nature of the latter, which presumably is less well understood than the former. If the analogy has really helpful explanatory value, there must be some reason for believing that the two series of events have enough in common for the explanation of one, mutatis mutandis, to provide at least a partial explanation of the other. This type of analogy must be distinguished from the purely metaphorical analogy in which the resemblances between two phenomena are used to add a picturesque note to an otherwise dull analysis and to help a reader to see more clearly the outlines of a process being described by enabling him to draw on what he knows in order to imagine the unknown. Analogies of this sort are not only useful but almost indispensable to human thought.The biological analogies of the firm are not of this metaphorical type or there would be no call to push them into service to help explain the development of firms" [@penrose1952biological]

"In the notion that a firm is an organism akin to biological organisms, there is an implication that, since all such organisms have something in common, we can use our knowledge of biological organisms to gain more insight into the firm" [@penrose1952biological]

**"The characteristic use of biological analogies in economics is to suggest explanations of events that do not depend upon the conscious willed decisions of human beings.** This is not, of course, characteristic of biology as such, for some branches of biology are concerned with learning processes and decision making, with purposive motivation and conscious choice in men as well as animals. In this, biology overlaps sociology and psychology and, in a sense, even economics. Information drawn from these branches of biology can be useful in helping us to understand the behavior of men and consequently of the institutions men create and operate. **In using such information, however, we are not dealing with analogies at all, but with essentially the same problems on a more complex scale**. But, paradoxically, where explicit biological analogies crop up in economics they are drawn exclusively from that aspect of biology which deals with the non-motivated behavior of organisms or in which motivation does not make any difference." [@penrose1952biological]. [**The use value of the biological analogy is found not in its metaphorical value, nor even in the use of the analogy itself, but in that it constitutes the lower level of the complex analysis suite from which emanates the behavior of individuals and the societies at a much higher level of analysis.**]{.underline}

"The desire to draw biological concepts into the explanation of social affairs is hard to understand since for the most part they add to rather than subtract from the difficulties of understanding social institutions (...). The appeal of such biological analogies to the social scientist plainly springs from a persistent yearning to discover "laws" that determine the outcome of human actions, probably because the discovery of such laws would rid the social sciences of the uncertainties and complexities that arise from the apparent "free will" of man and would endow them with that more reliable power of prediction which for some is the essence of "science." [@penrose1952biological]

"It should be noted that the distinction to be made is not that between human and non-human beings but between actions that are in some degree bound up with and determined by a reasoning and choosing process, no matter how rudimentary, and actions that are, as it were, "built into" the organism, or into the relationship between the organism and its environment, and cannot be altered by conscious decision of the organism itself." [@penrose1952biological]

"The information that we possess about the behavior of firms, small as it is, does furnish us with some plausible explanation of what firms are trying to do and why. **Biological explanations reduce, if they do not destroy, the value of this information and put nothing in its place**" [@penrose1952biological]

"The varieties of biological phenomena are so numerous that a parallel may be found somewhere for every conceivable type of social situation. There is even apparently a type of symbiotic growth among algae and fungi which combine to form characteristic lichens that can be compared to the growth of a firm by merger. Very curious "parallels" are sometimes drawn" [@penrose1952biological]

"But in seeking the fundamental explanations of economic and social phenomena in human affairs the economist, and the social scientist in general, would be well advised to attack his problems directly and in their own terms rather than indirectly by **imposing** sweeping biological models upon them" [@penrose1952biological]


## Main Types of Biological Analogies

"Biological analogies in particular have been widely used in discussions of the firm. Probably the best known and most common of these analogies is that of the **life cycle**, in which the appearance, growth and disappearance of firms is likened to the processes of birth, growth, and death of biological organisms. Marshall's reference to the rise and fall of the trees in the forest is an oft-quoted example of this type of analogy." [@penrose1952biological]

"Recently, two additional biological analogies have been presented -**a natural selection analogy**, dubbed by one writer viability analysis, and the **homeostasis analogy** designed to explain some aspects of the behavior of firms. The former, like the life cycle analogy, is for use in long-run analysis only. The latter is exclusively for short-run analyIn summary, this book has no content whatsoever. Both are supposed to represent improvements on the existing theory of the firm at the core of which lies the chief target of attack - the assumption that firms attempt to maximize profit" [@penrose1952biological]

"The chief danger of carrying sweeping analogies very far is that the problems they are designed to illuminate become framed in such a special way that significant matters are frequently inadvertently obscured. Biological analogies contribute little either to the theory of price or to the theory of growth and development of firms and in general tend to confuse the nature of the important issues." [@penrose1952biological]

## The "Life Cycle" Theory of the Firm (Kenneth Boulding)

"Implicit in the notion that firms have a"life cycle" analogous to that of living organisms is the idea that there are "laws" governing the development of firms akin to the laws of nature in accordance with which living organisms appear to grow, and that the different stages of development are a function of age." [@penrose1952biological]

"The purposes a life cycle theory of the firm would serve are obvious, yet the theory as a bare undeveloped hypothesis has existed for a long time and nothing has been done to construct from it a consistent theoretical system with sufficient content to enable it to be used for any purpose whatsoever. The basic hypothesis is not one from which significant logical consequences can be deduced, such as can be deduced,' for example, from the proposition that firms attempt to maximize profits. Supplementary hypotheses about the kind of organism the firm is and the nature of its life cycle are required. Although we have a respectable collection of information about firms, it has not stimulated economists even to suggest the further hypotheses necessary to the development of a life cycle theory of the firm. This, I think, is primarily because the available evidence does not support the theory that firms have a life cycle characterized by a consistent transition through recognizable stages of development similar to those of living organisms. Indeed, just the opposite conclusion must be drawn: the development of firms does not proceed according to the same"grim" laws as does that of living organisms. In the face of the evidence one is led to wonder why the analogy persists and why there is still a demand for a life cycle theory of the firm" [@penrose1952biological].

"Clearly the one thing a firm does not have in common with biological organisms is a genetic constitution, and yet this is the one factor that determines the life cycle of biological organisms." [@penrose1952biological] In this regard, see the use of the genetic analogy made by Nelson and Winter's @nelson1985evolutionary regarding what constitutes the genetic basis of the firm by assimilating it to the skills and abilities the firm posseses and that are transmitted from one employee to another in an evolutionary process along time.

*Willingness vs Not Willingness (Motivated vs Non-Motivated Behavior) in the growth pattern of the firm*: "We have no reason whatsoever for thinking that the growth pattern of a biological organism is willed by the organism itself. On the other hand, we have every reason for thinking that the growth of a firm is willed by those who make the decisions of the firm and are themselves part of the firm, and the proof of this lies in the fact that no one can describe the development of any given firm or explain how it came to be the size it is except in terms of decisions taken by individual men" [@penrose1952biological]. Sorry but I disagree. This statement conflicts with the perspective provided by Alchian @alchian1950uncertainty, according to which the behavior of the firm has an adoptive part (not linked to the will of the units that make the decisions in the firm), and an adaptive part (which does depend on the willpower of decision-makers).

"There can be no doubt, I think, that to liken a firm to an organism and then attempt to explain its growth by reference to the laws of growth of biological organisms is an ill-founded procedure (...) besides being ill-founded, this type of reasoning about the firm obscures, if it does not implicitly deny, the fact that firms are institutions created by men to serve the purposes of men. It can be admitted that to some extent firms operate automatically in accordance with the principles governing the mechanism constructed, but to abandon their development to the laws of nature diverts attention from the importance of human decisions and motives, and from problems of ethics and public policy, and surrounds the whole question of the growth of the firm with an aura of"naturalness" and even inevitability." [@penrose1952biological]. No one, not even Alchian, rests the firm's growth on a strictly "natural" conception, but rather on a combination between what is natural and what is directed by humans through their decisions.

"My original criticism of the "viability" analysis was simply that it gives an inadequate and inconsistent account of the significance of human motivation in economic affairs. (This is precisely the reason, incidentally, why the biological model fitted it so well" [@penrose1952biological]

## The Natural Selection (Viability) Analogy
"The idea of the survival of the fittest, however, was first suggested to Darwin by a work in the social sciences-Malthus on population." [@penrose1952biological]

"The purpose of the theory is to get around a logical difficulty alleged to be inherent in the assumption that firms attempt to maximize profits in a world characterized by uncertainty about the future. If uncertainty exists, firms cannot know in advance the results of their actions. There is always a variety of possible outcomes, each of which is more or less probable. Hence the expected outcome of any action by a firm can only be viewed as a distribution of possible outcomes, and it is argued that while a firm can select those courses of action that have an optimum distribution of outcomes from its point of view, it makes no sense to say that the firm maximizes anything, since it is impossible to maximize a distribution. Hence profit maximization as a criterion for action is regarded as meaningless. According to the "viability analysis," however, this is not a serious difficulty for the economist if he draws on the principle of natural selection and considers the adaptation required of firms by their environment." [@penrose1952biological]

"The alleged superiority of "viability" over marginal analysis lies in the claim that it is valid even if men do not know what they are doing. No matter what men's motives are, the outcome is de- termined not by the individual participants, but by an environment beyond their control. Natural selection is substituted for purposive profit-maximizing behavior just as in biology natural selection replaced the concept of special creation of species." [@penrose1952biological]

"To be sure, the two assumptions rest on vastly different factual foundations and should not be treated as analogous. We can only say that there is some evidence that such a psychological motivation is widely prevalent and that we have found we can obtain useful results by assuming it. If we abandon this assumption, and particularly if we assume that men act randomly, we cannot explain competition, for there is nothing in the reproductive processes of firms that would ensure that more firms would constantly be created than can survive; and certainly from observations of the real world we can hardly assume that competition is so intense that zero profits will result in the long run or that only the best adapted firms can survive."[@penrose1952biological]

"Underlying the viability analysis is the assumption that, even if firms can and do make more or less intelligent choices, they can do nothing in unpredictable ways to "force" the environment to "adopt," and thus make successful, the results of their action.
The concept of the environment of firms on which the economist using "viability" analysis bases his predictions is by no means clear." [@penrose1952biological]

"It is these unpredictable possibilities of altering the environment by man that create difficulties in comparing the economist to the biologist observing the processes of natural selection and studying the nature of adaptation. Animals, too, alter their environment, but in a rather un- conscious fashion without much deliberation about different probable outcomes of their actions. **The possibilities open to animals of affecting their environment in a given period of time are so much more restricted than those open to men that the biologist has a very much easier task, for the relative consistency of animal behavior and the relatively narrow limits within which animals can act give him a more secure basis for prediction**." [@penrose1952biological]

"It is not possible to go very far with this aspect of the matter because the authors of the viability approach have given us no hint of what they mean by the environment. . It is vaguely referred to as an "adoptive mechanism" (...)" [@penrose1952biological]

"By its very nature a prediction of the kinds of firms that will survive in the long run must take account of all the reactions and interactions that a given change in the environment will induce. With our present knowledge this is impossible, and the assertion that "the economist, using the present analytical tools developed in the analysis of the firm under certainty, can predict the more adoptable or viable types of economic interrelationships that will be induced by environmental change even if individuals themselves are unable to ascertain them" places the wrong interpretation on the kind of thing the economist can do. **If he can predict the consequences of environmental changes, it is not because certain types of interrelationships are more "viable" in a long-run sense, but because he has an idea of how people will behave**. He knows little about long-run viability since he knows very little about all of the secondary and tertiary reactions that will in the end determine the "conditions of survival"-at least he has as yet given little convincing evidence of such knowledge." [@penrose1952biological]

"After all, one of the more powerful effects of uncertainty is to stimulate firms to take steps to reduce it by operating directly on the environmental conditions that cause it and men have a greater power consciously to change their environment than has any other organism (...). It is by no means "straightforward" to assume non-motivation, for without motivation economic competition, leading to the elimination of all but the best adapted within a community, cannot be assumed. Hence, if the operation of natural selection through competition is made the guiding principle of the analytical technique, then an assumption equivalent to profit maximization must be made and the professed raison d'etre of the viability approach disappears." [@penrose1952biological]

## The Homeostasis Analogy
"Organisms are so constructed that there is a certain "equilibrium" internal condition which their bodies are organized to maintain. Any disturbance of the equilibrium sets forces in motion that will restore it (...) Once again we find the characteristic of the biological analogy - action taking place in human affairs without the intervention of human decisions based on deliberation and choice."[@penrose1952biological]

"Homeostasis is a word drawn from physiology, but it describes a characteristic of any activity that takes place within a framework so constructed that certain types of action are automatically induced without any interference from whatever agency is responsible for the construction. This notion can be extended from the physio-chemical reactions which take place within a living organism in order to maintain a constant internal environment, to include the operation of a thermostatically controlled heating or air conditioning system36 and even the conduct of a game of tag according to predetermined rules." [@penrose1952biological]

". There can be little doubt that the more complex an organ- ization becomes, the more necessary it is to establish areas of quasi- automatic operation. The importance of routine as a means of taking care of some aspects of life in order that others may be given more attention has frequently been stressed. The fact that many business decisions are not "genuine decisions," but are quasi-automatic and made routinely in response to accepted signals without a consideration of alternative choices has misled many into attacking the assumption that firms try to make as much money as they can-particularly where it can be shown that the rules governing the routine actions are not fully consistent with profit maximization" [@penrose1952biological]

"The theory of homeostasis provides a formal framework of explanation into which many routine responses can be fitted, but it throws no light at all - nor does it claim to- on why and how the "ideal" relationships between the relevant variables which the firm is now attempting to maintain were originally established or on the conditions under which decisions may be made to alter them. **Strictly speaking, the basic principle is not a biological one at all in spite of the name given it. It is a general principle of organization, examples of which may be found in biology, in mechanics and in social organization**, and if one chooses to introduce into economics another mysterious word borrowed from another science-well, that is a matter of taste"[@penrose1952biological]
