# Conclusion

The evolutionary analysis of systems fundamentally requires generating much more extensive and precise knowledge about individuals and populations, as well as about the periods and places in which they develop. This is self-evident when it comes to obtaining a deeper understanding of the reasons for change and diversity.

We also know today that systems do not evolve smoothly and continuously over long periods of time but do so based on pulses between periods of interruption that cause disruptive changes and the mass extinction of units.

Knowing the sequence of events that have shaped the evolutionary processes opens new analytical dimensions to the study of the evolutionary phenomenon and allows us to confront elements considered unpredictable until now in the course of evolution.

*It is certainly an exciting time for the field with the rapid expansion of science and practice. However, this growth has put positive education at risk of lacking a cohesive direction and of failing to build the cumulative evidence needed to advance the field.@waters2019search*

*In this paper we have argued that a meta-framework can prevent these risks by providing higher-order parameters that help us to guide future research and practise in ways that ensure more consistent, integrated, cohesive and perhaps even synergistic outcomes. The SEARCH framework, developed from a large-scale bibliometric analysis of the field combined with action research has been supported through a systematic review of evidence in the current paper which has shown that schools can build up each of the six pathways through interventions in and out of the classroom.@waters2019search*

*We offer this framework to our colleagues in the field and hope it is used far and wide to build rigorous research and reliable practices that help positive education to achieve the dual purpose put forward by Seligman et al. (2009) of boosting wellbeing and academic outcomes.@waters2019search*

*This review of involving the public in research agenda setting builds on the technique of framework analysis which has previously been described only for primary research.6 We found this approach useful for developing a conceptual framework of public involvement in research based on accessing and reviewing a broad literature. Our framework is consistent with analyses in the literature about empowerment for public involvement in public services more broadly. It is potentially applicable to a wide range of reports of public involvement in research and research-based activities. Use of the framework facilitates learning from many different strategies and reports of these, from informal reflections to formal research. Such a breadth can thus generate an overview of achievements to inform policies and practices in the area of public involvement in research. As with other systematic review methods, application of the framework also usefully identifies gaps in the literature which need to be filled in order to increase our understanding of how to promote public involvement and evaluate the effectiveness of different approaches.@oliver2008multidimensional*

## Recommendations
*We need more good quality research on interventions for particular social groups. Nonetheless, it is possible to derive a number of recommendations from the work described in this report. They are grouped into recommendations for developing future effective and appropriate interventions, systematic reviews, and views studies.@brunton2006synthesis*

*Type of recommendations: Recommendations for developing effective and appropriate interventions / Recommendations for future views studies / Recommendations for future systematic reviews. @brunton2006synthesis*
The