# Implications

## Evolutionary analyst

One of the practical benefits derived from the present proposal of formulating an evolutionary systems analytical framework is to determine the need to have professionals with an evolutionary analyst profile. An evolutionary analyst is understood to be an academic or professional who has a clear and deep understanding of the evolutionary functioning of systems and who is capable of using rigorous analysis and tools to determine the factors that explain their essence and elements of change.

## Prediction ability

If we are able to acquire a deep understanding of the functioning of the evolutionary system, its components, behaviors and flow of changes, we can then better foresee in which direction the evolutionary system is moving and glimpse whether the system has the capacity to survive or, on the contrary, is doomed to disappearance.

It is worth considering the possibility of whether, based on increasingly deeper knowledge of the evolution of a system, it would be possible to act on the future of the system. In other words, if it could be feasible to design your own plan and carry it out based on the knowledge generated about the evolution of the system.

To what extent is the system under observation random in change or does it evidence a logic that can be known and even altered based on our desires or needs?

## Manipulation of the system and its programmability
If they were really able to manipulate the system as we wish, on what elements would it be most feasible to do so? Would it be possible to act on both the structural and behavioral elements, only on one of them? Being able to act on a known evolutionary system would open new and great opportunities to design systems that meet a wide diversity of needs.

The above would necessarily entail having to assess the ethical problems of altering the course of nature and the new problems that would emerge by distorting the natural mechanisms of the functioning of life and society. The opposite position would be to conclude that the system is unalterable and we cannot intelligently design it to satisfy our desires.

Society would go from a stage in which social systems are considered elusive to another in which we would be able to know to what extent their evolution is random, to what extent there is causality and to what extent they are programmable.

## Inform and activate policies

An evolutionary analysis framework can serve to inform who cannot support themselves, namely, who is more likely to survive and continue competitive, and who is threatened by disappearance.

Identifying who dominates over whom, that is, elucidating the relationships and power structures has great significance, but it is also a way to understand how species advance. In fact, the process of replacement or extinction of species is an essential aspect to understand human progress.

The level at which the analyst expects to inform policy, or the level of contribution expected by decision makers from an evolutionary model, is a factor in determining the level of analysis to be used in the "struggle for existence."

Additionally, if education (education policies) could improve individuals, the benefits could perhaps be passed on through inheritance (this is a Lamarckian view).

## Overcoming the barriers that prevent systematic struggle

From the RQs: Another question that the evolutionary analyst can try to resolve is whether the individual **permits the struggle** to take place and, if not, to what extent this weakens the individual and, therefore, that the individual enters into a process of degeneration that leads to a replacement by another individual.

This leads us to the recommendation, in some circumstances mediated by policies, that the struggle does not have constraints that condition it. Thus, as the environment continues to pose challenges that must be faced (resolved) by the individual, progress will continues.

## Eugenics of individuals
The above leads us to the problem of eugenics, and the reflection on to what extent the system must ensure that the selection produces and there are no barriers for it to unfold its effects.

## The connection with complex systems
The analysis of evolutionary systems demonstrates a connection with complex systems, such that species should be seen as complex systems with an enormous amount of variation, stimulated by selection.
