# Reasons

Alchian @alchian1950uncertainty submits that there is a double reason to ask for a new economic analysis. These are an incomplete information in the functioning of the economic system and uncertain foresight. The latter recognizes the role of prediction that every economic analysis must play if it's to be good.

This vision proposed by Alchian in 1954 moves away from the typical axiom of **"profit maximization"** and the prediction of the individual behavior of the firm as primary means for understanding the behavior of the firm. Instead, Alchian provides a solution by suggesting the adoption of biological evolution and natural selection as thinking paradigms. The introduction of this new approach allows Alchian to treat an economic system as an adaptive "mechanism" able to choose among those "(...) exploratory actions generated by the adaptive pursuit of"success" or "profits"."

"The assumption that firms try to maximize their profits is rejected by Alchian, not for empirical reasons arising from a study of how firms actually do behave, but for logical reasons arising from the existence of uncertainty. He holds that in the presence of uncertainty no unique maximum profit position exists; that it is therefore impossible to give any meaning to the proposition that firms try to maximize profits; and that, consequently, a mere desire for maximum profits provides no guide for action. On the other hand, he is pre- pared to admit "motivated purposive behavior" and to recognize that firms are in business to make a profit, although apparently he feels that even this modified motivation is going a bit far. 

Once it is allowed that firms do try to make profits, it is not difficult to go a bit further and assume that in general they tend to try to make, if they think they can, a bit more profit than they are making. The question, then, is what difference does it make whether any individual firm knows the best way of going about its business - or indeed whether there is any "best" way before the event. This would make a great deal of difference if the economist were attempting to predict the actions of any particular firm. But the economist does not attempt such predictions - nor could he succeed if he tried, as Alchian rightly emphasizes. **The economist uses the model of the profit-maximizing individual firm, not to predict the actual conduct of any firm, but merely as an analytical technique to assist him in understanding the effect of change on prices, production, employment, etc.** For this purpose it makes no difference whether the conduct of any particular firm can be predicted, whether any firm at all can actually succeed in maximizing profits or even whether uncertainty makes it impossible to say that any particular profit is a maximum" [@penrose1953biological] En realidad lo que está diciendo aquí Penrose es que sus dos enfoques, el suyo y el de Alchian, se parecen más de lo que parece porque ambos tratan de servir como instrumentos para explicar el comportamiento de la firma, no para predecir la conducta de la firma.

"Attempts radically to alter the framework of existing theory are always likely to meet resistance, but progress comes from the interaction between innovation and resistance to innovation" [@penrose1953biological]

A valuable benefit of this new perspective is that economic analysts can, according to Alchian, now confront problems that were previously considered aberrant or that required an ad-hoc analytical apparatus.Ultimately, it is an approach that widens the capabilities of economic analysis and prevents the analyst from having to introduce unrealistic assumptions to reach any coherent result.

However, Alchian's innovative approach remains half-finished because he assumes that he will continue using the same conceptual apparatus of his analytical predecessors. That is to say, the same concepts used in the type of analysis based on profit maximization seem to continue serving under its new perspective.

"Thus a certain elementary theoretical function (i.e. prices and demand) seems adequately to describe actual hu- man behavior; other elementary functions may describe technological facts, such as production conditions. Our task is to explain, in terms of such elementary relations, other more complicated ones which we also observe" "Cita del autor: R. Bye said (p. 282): "The ultimate justification of all science is the power it gives us to make things go the way we want them to." Whether ultimate or not, it is an important object of science. "[@marschak1941methods]

"
