# Scheme

It is important to clearly establish the differences that distinguish an evolutionary process from another of change or transformation. Although these are related concepts in evolutionary theory, they actually denote different processes that act on different agents, which is why they tend to be confusing even among some specialists.

Evolution is an overarching process that drives change in populations over generations. This means that evolutionary processes do not operate at the level of a specific individual or organism, which would only change or transform. Evolution therefore represents the cumulative effect of the inherited changes made by the characteristics of the individuals of a population, on which a selection process operates affecting the frequency of traits within a population over time. Change encompasses a broad spectrum of morphological or behavioral alterations within individuals from a variety of factors, including environmental pressures and reproductive patterns. Transformation suggests more profound or significant shifts in form, structure or function of individuals.

**ORIGIN**

The problem of the origin is associated with that of the "Problem of Generation" and its accompanying theories of generation. An analysis of the origin involves the need to explore for evidence of the past in search for a better system. The following are some of the theories to consider when addressing the problem of generation of the original structure:

-   Spontaneous generation

-   Preformationism (forms that are predetermined)

-   Pre-existence

-   A mold that is fixed.

**STRUCTURE**

The main issue when considering Structure is to establish what the analytical unit of the system is (and what its main basic components are). In the case of natural evolutionary theory, this unit has traditionally been the organism, but also the population and later, after modern synthesis, the gene. It is the analyst's job to determine as clearly as possible which is the "unit" on which the evolutionary analysis of the system will focus.

**ENVIRONMENT**

The environment surrounding the chosen unit of analysis exerts various types of forces that act on the structure to provoke a process of change, with greater or lesser intensity, and in one direction or another.

The forces of change originating in the environment force the unit to change, so it is essential that the analyst analyze the environment in depth as a key impact driver, understanding the role of the environment in the evolutionary process of the system.

The connection between the environment and the origin is a key issue as well, since the direction of the change, if it exists, and the intensity or depth of the change that may take place in the structure of the unit may sometimes depend on it.

It is important when analyzing the environment to specify the type of force applied to the structure, and its sources in said environment.

**BEHAVIOR**

Behavior is the way in which the structure articulates a response to the pressure exerted by environmental forces. Behavior establishes the boundaries within which the structure is capable of absorbing the forces of the environment and giving an adaptive response to the new situation or challenge posed by the environment.

The result of the behavior, which takes place within the boundaries established by the structure of the unit, can give rise to three types of adaptive responses by the system:

-   New system qualities (traits)
-   Loss of system qualities (traits)
-   Modification of system qualities (traits)

**CHANGE**

Both the structure and the behavior are permanently immersed in a process of change, since the unit is always sensitive to the forces exerted on it originating in the environment. The overall evolutionary process of the unit will depend on the way in which these forces affect the unit.

The characterization of the change process must be carried out considering the following key dimensions, all of them closely related:

1.  The direction or trend of the change process. This question has historically been part of the discussion on evolutionary theory, with different approaches given by different authors.

2.  The change driver, whether it is a single one or a set of drivers that configure the change process.

3.  The mechanics of the process, whether gradual and slow, or sudden and in jumps, or any intermediate alternative in the continuum formed by these two extremes.

4.  The time scale on which the change process takes place. This can develop over a vast amount of time or a small amount of time, or somewhere in between.

Some important considerations to keep in mind are that the process of change always implies progress, but it can also involve regression.

**DISCUSSION**

***On the Origin***

The idea of the Origin is consubstantially associated with the idea of an end, since everything that begins must necessarily have an end.

***On the Environment***

We do not know the forces (and their sources) that operate driving the process of change in the individuals of a population.

Apart from the forces that operate at the level of individuals, it is necessary to know what the transmission mechanisms are like from the environment to the individual, between individuals, and vice versa, from the individual to the environment. 

What is the materiality of the pressure for change exerted by an environmental force?

***On Change***

We know what an individual is today, but we do not know how an individual became what it is today. This necessarily raises the need to study the historical past as a source of knowledge to understand the process of change or evolution followed.

It is necessary to know which components of the individual's structure (or flows) the forces of the environment act on, or on which behaviors the forces of the environment have an impact.

Also relevant is the question of how the development process of an individual is like, both before conception (embryonic development) and during its life period.

Does the change caused by forces in the environment respond to any reason or objective? Is there any direction, goal or trend? And if there is one, what is the justification for it to exist? Is there any type of constraint associated with the development of the individual that conditions or limits the process of change?  Can we rule out that the individual's process of change does not have a teleological character (e.g. a guiding principle, a force, etc.) towards a specific end/goal?

To what extent is the timeline for the adoption of changes a key factor that determines the individual results of the change? It is key when analyzing change to elucidate the timeline in which it unfolds.

***On Evolution***

When studying the evolution of a population, classification or taxonomy becomes relevant, since it requires discipline in the knowledge of the building blocks and the relationships (or degrees of relationships) between individuals.This generally opens new avenues to trace (and understand) the past of evolution and be able to foresee the next steps it will go through.
